spring:
  application:
    name: application80
  zipkin:
    base-url: http://124.70.220.74:9411/
  sleuth:
    sampler:
      probability: 1
server:
  port: 80

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/

