server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 111.230.23.30:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'




