server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
    fetch-registry: true
spring:
  application:
    name: cloud-provider-hystrix-order
feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。